project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!internal/"

bibliography: references.bib
csl: apa-6th-edition.csl

website:
  title: "Predictive Analytics (PA) for Improving Services"
  page-navigation: true
  back-to-top-navigation: true
  sidebar:
    background: light
    foreground: dark
    style: "docked"
    search: true
    collapse-level: 1
    pinned: false
    contents:
      - index.qmd
      - materials.qmd
      - section: "Defining PA for improving services"
        contents:
          - paforimprovingss_define.qmd
          - paforimprovingss_learn.qmd
          - paforimprovingss_limitations.qmd
          - paforimprovingss_ethics.qmd
          - paforimprovingss_context.qmd
      - section: "Scoping a PA project"
        contents:
          - scoping_ex.qmd
          - scoping_usefindings.qmd
          - scoping_what.qmd
          - scoping_who.qmd
          - scoping_when.qmd
      - section: "Conducting a PA proof-of-concept"
        contents:
          - poc_importance.qmd
          - poc_learners.qmd
          - poc_benchmark.qmd
          - poc_compare.qmd
      - section: "Data for PA: PART 1"
        contents:
          - data_overfitting.qmd
          - data_split.qmd
          - data_identify.qmd
          - data_test.qmd
          - data_trainvalidate.qmd
          - data_splitconsiderations.qmd
      - section: "Data for PA: PART 2"
        contents:
          - data2_overview.qmd
          - data2_whymissing.qmd
          - data2_missingpredictors.qmd
          - data2_missingoutcomes.qmd
          - data2_EDA.qmd
          - data2_extract.qmd
          - data2_changesovertime.qmd
      - section: "Introduction to the PA Templates"
        contents:
          - toolset_overview.qmd
          - toolset_datamodel.qmd
          - toolset_firstlook.qmd
          - toolset_tidymodels.qmd
      - section: "Modeling approaches"
        contents:
          - methods_overview.qmd
          - methods_logistic.qmd
          - methods_lasso.qmd
          - methods_rf.qmd
          - methods_xgboost.qmd
          - methods_naivebayes.qmd
          - methods_svm.qmd
          - methods_nn.qmd
          - methods_guidance.qmd
      - section: "Evaluating and comparing predictive performance"
        contents:
          - perform_output.qmd
          - perform_confusionmatrix.qmd
          - perform_thresholdinvariant.qmd
          - perform_goals.qmd
          - perform_selectthreshold.qmd
      - section: "Evaluating and comparing bias"
        contents:
          - bias_intro.qmd
          - bias_modeling.qmd
          - bias_use.qmd
          - bias_define.qmd
          - bias_context.qmd
          - bias_toolset.qmd
          - bias_address.qmd
      - section: "Selecting and validating a learner"
        contents:
          - "Considerations for selecting a learner"
          - "Validating a learner"
      - section: "Understanding and communicating results"
        contents:
          - "Results at the individual level"
          - "Results at the aggregate level"
          - "What can we say about which predictors matter most?"
          - "Reviewing limitations and ethical considerations"
      - section: "Deploying predictive analytics"
        contents:
          - "Deciding whether PA should be deployed"
          - "Approaches for deployment"
          - "Monitoring performance and fairness over time"

      - section: "Additional optional material"
        contents:
          - OptionalPAvsInfStat.qmd
    # - section: "Issue Log"
    #   contents:
    #     - issuelog.qmd

    # - title: "References"
    #   contents:
    #     - reference.qmd

format:
  html:
  # theme: cerulean
    number-sections: true
    number-depth: 1
  #    css: style.css
    grid:
      sidebar-width: 400px
      body-width: 1200px
      margin-width: 100px
    #      gutter-width: 1.5rem
#     pdf:
#      documentclass: scrreprt
#
#   editor: visual
#
