project:
  type: website
  output-dir: docs

bibliography: references.bib
csl: apa-6th-edition.csl

website:
  title: "Predictive Analytics for Improving Services"
  page-navigation: true
  back-to-top-navigation: true

  navbar:
    background: primary
    search: true
    left:
      - text: "Course overview"
        file: index.qmd
      - text: "Course materials"
        file: materials.qmd
      - text: "Assignments and project"
        file: project.qmd
      # - text: "References"
      #   file: references.qmd

  sidebar:
    - title: "index"
      style: "floating"
      contents:
        - course_description.qmd
        - "Syllabus"
        - "Classroom expections and norms"
        - "Six ways to get help"
        - "Grading"

    - title: "materials"
      style: "floating"
      contents:
        - materials.qmd
        - section: "Predictive analytics to improve social services - an overview"
          contents:
          - paforimprovingss_define.qmd
          - paforimprovingss_learn.qmd
          - paforimprovingss_limitations.qmd
          - paforimprovingss_ethics.qmd
          - paforimprovingss_context.qmd
        - section: "Scoping a predictive analytics project"
          contents:
          - scoping_ex.qmd
#         - scoping_stakeholders.qmd
#         - scoping_usefindings.qmd
#         - scoping_what.qmd
#         - scoping_who.qmd
#         - scoping_when.qmd
        - section: "Conducting a proof of concept"
        - section: "Data for predictive analytics PART 1"
        - section: "Data for predictive analytics PART 2"
        - section: "Specifying learners PART 1"
        - section: "Specifying learners PART 2"
        - section: "Evaluating and comparing predictive performance"
          contents:
          # - performance_metrics_PLACEHOLDER.qmd
        - section: "Evaluating and comparing bias"
        - section: "Selecting and validating a learner"
        - section: "Understanding and communicating results"
        - section: "Deploying predictive analytics"
        - section: "Additional optional material"
          contents:
          - OptionalPAvsInfStat.qmd
        - section: "Issue Log"
          contents:
          - issuelog.qmd

    - title: "References"
      contents:
        - reference.qmd


# format:
#   html:
#     theme: cosmo
#     css: styles.css
#     toc: true
#
# editor: visual

# bibliography: references.bib
#
format:
  html:
#    theme: cerulean
    number-sections: true
    number-depth: 1
#    css: style.css
    grid:
      sidebar-width: 400px
      body-width: 1200px
      margin-width: 100px
#      gutter-width: 1.5rem
#   pdf:
#     documentclass: scrreprt
#
# editor: visual
#
