project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!internal/"

bibliography: references.bib
csl: apa-6th-edition.csl

website:
  title: "Predictive Analytics (PA) for Improving Services"
  page-navigation: true
  back-to-top-navigation: true
  sidebar:
    background: light
    foreground: dark
    style: "docked"
    search: true
    collapse-level: 1
    pinned: false
    contents:
      - index.qmd
      - materials.qmd
      - section: "Defining PA for improving services"
        contents:
          - paforimprovingss_define.qmd
          - paforimprovingss_learn.qmd
          - paforimprovingss_limitations.qmd
          - paforimprovingss_ethics.qmd
          - paforimprovingss_context.qmd
