project:
  type: website
  output-dir: docs

website:
  title: "Predictive Analytics for Improving Social Services"
  page-navigation: true
  back-to-top-navigation: true

  navbar:
    background: primary
    search: true
    left:
      - text: "Course overview"
        file: index.qmd
      - text: "Course materials"
        file: materials.qmd
      - text: "Project"
        file: project.qmd
      - text: "References"
        file: references.qmd

  sidebar:
    - title: "index"
      style: "floating"
      contents:
        - course_description.qmd
        - "Syllabus"
        - "Classroom expections and norms"
        - "Six ways to get help"
        - "Grading"

    - title: "materials"
      style: "floating"
      contents:
        - materials.qmd
        - section: "How can predictive analytics be used to improve social services?"
          contents:
          - paforimprovingss_define.qmd
          - paforimprovingss_learn.qmd
          - paforimprovingss_limitations.qmd
          - paforimprovingss_ethics.qmd
          - paforimprovingss_context.qmd

    - title: "References"
      contents:
        - reference.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
  # sidebar:
  #   style: docked
  #   background: light
  #
#   chapters:
#     - index.qmd
#     - part: "How can predictive analytics be used to improve social services?"
#       chapters:
#         - paforimprovingss_define.qmd
#         - paforimprovingss_learn.qmd
#         - paforimprovingss_limitations.qmd
#         - paforimprovingss_ethics.qmd
#         - paforimprovingss_context.qmd
#
#     - part: "Scoping a PA Project"
#       chapters:
#         - scoping_ex.qmd
#         - scoping_stakeholders.qmd
#         - scoping_usefindings.qmd
#         - scoping_what.qmd
#         - scoping_who.qmd
#         - scoping_when.qmd
#     - part: summary.qmd
#     - references.qmd
#
# bibliography: references.bib
#
# format:
#   html:
#     theme: cerulean
#     number-sections: true
#     number-depth: 1
# #    css: style.css
#     grid:
#       sidebar-width: 475px
# #      body-width: 900px
#       margin-width: 100px
# #      gutter-width: 1.5rem
#   pdf:
#     documentclass: scrreprt
#
# editor: visual
#
