---
title: "Syllabus"
author: "Kristin Porter"
date: "`r Sys.Date()`"
output: pdf_document
---


## Course Details

**DSC495 Special Topics in Data Science: Predictive Analytics for
Improving Services**

|                                                                                                          |                                                                                              |
|--------------------------------------|----------------------------------|
| **Semester:** Fall 2023                                                                                  | **Section:** 613                                                                             |
| **Instructor:** Kristin Porter                                                                           | **Class Meetings:** Thursdays                                                                |
| **Email:** kristin.porter\@keporterconsulting.com                                                        | **Time:** 3-3:50 PM EST                                                                      |
| **Office hour location:** [Zoom link](https://zoom.us/j/7807607669?pwd=WktiaGY4WStOSG9HNlVhREpqclp1Zz09) | **Location:** [Zoom link](https://zoom.us/j/7807607669?pwd=WktiaGY4WStOSG9HNlVhREpqclp1Zz09) |
| **Office hours:** TBD                                                                                    | **This meeting is required.**                                                                |
| **Last updated:** 08/04/2023                                                                                 | **Credit hours:** 1                                                                          |

## Course Description

#### Description:

For-profit companies, nonprofit service providers and government
agencies often use predictive analytics to improve their services.
Predictive analytics harnesses historical data and may incorporate
machine learning to model future outcomes. Students will explore the
value, limitations and ethical considerations of predictive analytics
when used to improve services. Using their own dataset or one provided
by the instructor, students will learn and apply a practical approach
for planning, implementing and assessing a predictive analytics project.
The instruction will highlight topics related to data preparation, model
training and selection, validation, fairness, transparency and
communication of results.

#### **Prerequisites:**

Students should have familiarity with R Studio and some experience using
R to manipulate data and run basic descriptive statistics.

#### Learning objectives:

-   Gain the ability to critically assess the potential value and
    limitations of predictive analytics for improving services when
    applied to a particular context and data system.

-   Understand how results from predictive analytics can provide
    actionable insights for improving services.

-   Understand how to plan and implement all steps of a predictive
    analytics workflow using open-source code templates. The steps
    include planning the analysis to match goals, exploring and
    preparing data, specifying and training models, and assessing the
    validity and bias of predictive models -- all while prioritizing
    best-practices for ethics, transparency and replication.

-   Gain a high-level understanding of sta(s(cal concepts for optmizing
    predictive analytics and have op(onal choices to dive more deeply.

-   Present predictive analytics results using an R notebook and clearly
    communicate interpretations, cautions and recommendations.

#### **About the Data Science Academy:**

Welcome to an NCSU Data Science Academy Course! In July 2021, the
universitywide and interdisciplinary Data Science Academy was launched
to meet the growing needs of data science research, education and
expertise in North Carolina and beyond. At NC State, Data Science is for
Everyone. Data Science Academy (DSA) Courses are designed to make sure
that each student can pursue appropriate level challenges through
opportunities to make choices and pursue projects of interest. Whether
you have never thought about data science before or bring experience and
expertise, we welcome you. Our goal is that after each DSA class you
want to learn more! [For more on the DSA course
design](https://docs.google.com/document/d/1RuzVw31v07llFlQK6nj9YvhkX9WGqh5KAE8CBAuHuEo/view). 

#### **About DSA research:**

To make sure that we are providing an appropriate collection of courses
with a variety of challenge levels within each course, we will be
collecting data to help us build a practice of continuous improvement.
The purpose of the data is to evaluate the DSA and how well we are
serving our students. We hope to be able to share what we learn with
other universities and researchers - we will ask your permission at the
beginning of the course to be able to share your anonymized data when we
communicate about the work of the DSA. 

## Resources

There is no textbook for this class. All reading materials are provided
within this website and can be accessed in the "Course Materials" tab at
the top of the page. The course materials includes text developed by the
instructor as well as links to helpful reading, which may be required or
optional as noted.

## Grading

FORTHCOMING

## Course Schedule

The course schedule is linked
[here](https://docs.google.com/document/d/1f28I3bYeAAqa90ohFqAk3MSSDiieYdN0kKheXaXk0z0/edit?usp=drive_link).

## Attendance Policy

For complete attendance and excused absence policies, please see
http://policies.ncsu.edu/regulation/reg-02-20-03. For coronavirus
related attendance guidance, see the "coronavirus information" section.

**Attendance Policy.** Students are expected to attend class regularly.
Since we only meet once a week, each class is vitally important to keep
on track during the semester.

**Absences Policy.** Students should notify the instructor that they
will be unable to attend class and schedule a time to meet with the
instructor to review materials they missed during class time.

**Makeup Work Policy.** Makeup work will be allowed if the student
notifies the instructor at least one day before an assignment is due to
arrange for a deadline extension. Notification given on the due date
will be considered on a case-by-case basis.

## Academic Integrity

Students are required to comply with the university policy on academic
integrity found in the Code of Student Conduct found at
http://policies.ncsu.edu/policy/pol-11-35-01.

Students are expected to produce work that they personally completed and
in accordance with the instructions given for the assignment, project,
test or quiz. Work copied from other students, completed by another
individual, or directly taken from other sources without appropriate
attribution will be in violation of academic integrity. Students are
expected to follow the Code of Student Conduct (NCSU POL11.35.01) and
Pack Pledge, and violations of academic integrity will be handled in
accordance with the Student Discipline Procedures (NCSU REG 11.35.02).

**Honor Pledge.** Your submission on any test or assignment indicates "I
have neither given nor received unauthorized aid on this test or
assignment." Digital Course Components Students may be required to
disclose personally identifiable information to other students in the
course, via digital tools, such as email or web-postings, where relevant
to the course. Examples include online discussions of class topics, and
posting of student coursework. All students are expected to respect the
privacy of each other by not sharing or using such information outside
the course.

## Digital Course Components

Our primary form of communication outside of online Zoom meetings will
be through Moodle. Students are expected to monitor Moodle for
announcements, assignments, and other information during the semester.
Assignments. Assignments and final projects may be given and submitted
through Moodle.

## Accommodations for Disabilities

Reasonable accommodations will be made for students with verifiable
disabilities. In order to take advantage of available accommodations,
students must register with the Disability Resource Office at Holmes
Hall, Suite 304, Campus Box 7509, 919-515-7653. For more information on
NC State's policy on working with students with disabilities, please see
the Academic Accommodations for Students with Disabilities Regulation
(REG02.20.01). Non-Discrimination Policy NC State provides equal
opportunity and affirmative action efforts, and prohibits all forms of
unlawful discrimination, harassment, and retaliation ("Prohibited
Conduct") that are based upon a person's race, color, religion, sex
(including pregnancy), national origin, age (40 or older), disability,
gender identity, genetic information, sexual orientation, or veteran
status (individually and collectively, "Protected Status"). Additional
information as to each Protected Status is included in NCSU REG 04.25.02
(Discrimination, Harassment and Retaliation Complaint Procedure). NC
State's policies and regulations covering discrimination, harassment,
and retaliation may be accessed at
http://policies.ncsu.edu/policy/pol-04-25-05 or
https://oied.ncsu.edu/divweb/. Any person who feels that he or she has
been the subject of pro hibited discrimination, harassment, or
retaliation should contact the Office for Equal Opportunity (OEO) at
919-515-3148.

## Technology Requirements

This course may require particular technologies to complete coursework.
Specifically, students will need R and R Studio. To avoid challenges
that may arise due to different versions of packages, the instructor is
providing access to code at the this link. Students will need to create
accounts with their email address in order to gain access.

If you need access to additional technological support, please contact
the Libraries' Technology Lending Service:
[https://www.lib.ncsu.edu/devices. ](https://www.lib.ncsu.edu/devices.)

## Resources

These are difficult times, and academic and personal stress is a natural
result. Everyone is encouraged to take care of themselves and their
peers. If you need additional support, there are many resources on
campus to help you: 

• Counseling Center https://counseling.dasa.ncsu.edu/ 

• Health Center https://healthypack.dasa.ncsu.edu/ 

• If you or someone you know are experiencing food, housing or financial
insecurity, please see the Pack Essentials Program
https://dasa.ncsu.edu/pack-essentials/ 

**Supporting Fellow Students in Distress.** As members of the NC State
Wolfpack community, we each share a personal responsibility to express
concern for one another and to ensure that this classroom and the campus
as a whole remains a healthy and safe environment for learning.
Occasionally, you may come across a fellow classmate whose personal
behavior concerns or worries you, either for the classmate's well-being
or yours. When this is the case, I would encourage you to report this
behavior to the NC State's Students of Concern website:
https://prevention.dasa.ncsu.edu/nc-state-cares. Although you can report
anonymously, it is preferred that you share your contact information so
they can follow-up with you personally. I may also make a referral to
the CARES program if I notice you are having a difficult time. If you
don't know who to talk to or which steps to take, please don't hesitate
to come talk to me and I will help you the best I can. 

Students are responsible for reviewing the NC State University Policies,
Rules, and Regulations (PRRs) which pertain to their course rights and
responsibilities, including those referenced both below and above in
this syllabus:

Equal Opportunity and Non-Discrimination Policy Statement:
https://policies.ncsu.edu/policy/pol-04-25-05 with additional references
at https://oied.ncsu.edu/divweb/policies/

Code of Student Conduct: https://policies.ncsu.edu/policy/pol-11-35-01.

\
