---
title: What are we trying to predict?
---

We want to predict employment. But how, exactly are we defining and measuring employment? We need to define it very precisely, considering:

-   What is most important to the TANF program's goals?

-   What can be measured - reliably and consistently over time - with the available data?

In our example, we will focus on just measure, but multiple measures of employment that make sense for the goals of the project could be analyzed.

The selected precise outcome measure is: whether a client is employed in a job that is covered by unemployment insurance (UI) for all of the first 3 quarters following program exit. The measure is coded as 1 when this is true and 0 otherwise.

This choice was made because:

1.  Employment sustainability was a priority for the TANF program and this measure captures success in employment sustainability two ways:

    -   If a client completes the program's education and training program and then is employed for 3 consecutive quarters, then the measure equals 1 for success.

    -   If a client leaves the program early but then is employed for 3 consecutive quarters, then the measure equals 1 for success. The measure is coded as 1 when this is true and 0 otherwise.

        Important note: if we defined the outcome measure as "whether a client is employed in a job that is covered by unemployment insurance (UI) for all of the first 3 quarters following program *completion* instead of *exit*, then our measure would be problematic. Those who left the program because they got a job would not be considered a success and coded as 0. This could lead to misdirecting resources to clients who are likely to get and keep jobs, just early.)

2.  UI data is the data relied on for employment information. These data cover most jobs, but miss things like a lot of gig work and self-employment.


However, after defining this measure, the project decided to code this outcome in the negative -- so that we were estimating likelihoods of whether someone does not achieve the employment outcome. Therefore, our predicted likelihoods represent risk scores.
