---
title: "How will findings be used?"
editor: 
  markdown: 
    wrap: 72
---

The social services department had an established practice of offering
additional support to clients requiring extra assistance. This
encompassed:

-   Initiating check-in calls with clients,

-   Facilitating supplementary casework sessions, and

-   Arranging extra workshops to enhance job search and skills.

Given the department's constraints in terms of staff and financial
resources, their aim was to effectively direct extra services to those
in greatest need. They recognized that their current method of
prioritizing such clients could be enhanced by distilling a wide
range of potentially predictive information into a single "risk score."

A few things to note:

-   They did not want, nor did the project team recommend, for their 
    decision-making process to become completely dependent on the risk scores.

-   Instead, the risk scores could potentially provide a valuable piece
    of information (if we could validate good predictive performance
    and minimal bias).

-   The department planned to train caseworkers in how to interpret and
    incorporate the risk score into their decision-making and
    prioritizing.

-   The department also wanted to look at how risk scores varied across
    and within populations served by offices throughout the state. This analysis
    could help them understand which offices were more in need of
    support for reaching out to clients and for planning workshops.

This information about how the department plans to use the information
can guide how we scope the predictive analytics project.

Remember, we also want to frequently check in with our ethical
considerations. [What ethical considerations do we want to be careful
about as we proceed?]{style="color:green"}
